### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by vivekmishra8739** [ZhuMSLab/DecoMetDIA#1]
I am trying to install the MetDIA but I am getting this message: 

Installing package into ‘C:/Users/VIVEK/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)

Can you please let me know how to fix this problem?
![Capture](https://user-images.githubusercontent.com/31123784/64869668-6e2a1680-d65f-11e9-8f11-15aea760dbb1.PNG)

**Comment by ZhuMSLab** [comment]
I am afraid the 'DecoMetDIA-master.zip' was not a windows binary package. You should install it as a source package. I did not build a windows binary version. I am sorry for that. You can just using `devtools::install_github()` method from the source code.

The lib unspecified was not a problem as it will be installed to the default Rlibrary path.
